import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from typing import Dict, Any, List
from backend.utils.indian_formatter import format_inr, format_number_inr

def generate_pdf_report(kpis: Dict[str, Any], insights: List[Dict[str, Any]], top_products: List[Dict[str, Any]], categories: List[Dict[str, Any]]) -> bytes:
    """Generates an executive PDF report byte stream using ReportLab."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0F172A'), # Slate 900
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748B'), # Slate 500
        spaceAfter=15
    )

    section_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1E293B'), # Slate 800
        spaceBefore=12,
        spaceAfter=8
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#334155')
    )

    story = []

    # Title Banner
    story.append(Paragraph("Sales & Revenue Executive Summary Report", title_style))
    story.append(Paragraph("Generated by Business Analytics Engine • Currency: INR (₹)", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#6366F1'), spaceAfter=15))

    # KPI Summary Table
    story.append(Paragraph("Executive Key Performance Indicators", section_style))
    
    kpi_data = [
        ["Total Revenue", "Total Profit", "Total Orders", "Profit Margin"],
        [
            kpis.get("total_revenue_formatted", "₹0"),
            kpis.get("total_profit_formatted", "₹0"),
            kpis.get("total_orders_formatted", "0"),
            f"{kpis.get('profit_margin', 0)}%"
        ],
        ["Total Sales Volume", "Average Order Value", "Total Customers", "Revenue Growth"],
        [
            f"{kpis.get('total_sales', 0)} units",
            kpis.get("avg_order_value_formatted", "₹0"),
            str(kpis.get("total_customers", 0)),
            f"{kpis.get('revenue_growth', 0):+.1f}%"
        ]
    ]

    kpi_table = Table(kpi_data, colWidths=[130, 130, 130, 130])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#F1F5F9')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#0F172A')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 2), (-1, 2), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 15))

    # Key Business Insights Section
    story.append(Paragraph("Key Automated Business Insights", section_style))
    for ins in insights[:5]: # top 5 insights
        p_title = f"<b>• {ins.get('title', 'Insight')}</b>: {ins.get('text', '')}"
        story.append(Paragraph(p_title, body_style))
        story.append(Spacer(1, 4))
        
    story.append(Spacer(1, 10))

    # Category Breakdown Table
    story.append(Paragraph("Category Performance Breakdown", section_style))
    cat_headers = ["Category", "Revenue", "Profit", "Volume", "Rev Share", "Profit Margin"]
    cat_rows = [cat_headers]
    for c in categories[:6]:
        cat_rows.append([
            c.get("category", ""),
            c.get("revenue_compact", ""),
            c.get("profit_formatted", ""),
            str(c.get("quantity", 0)),
            f"{c.get('revenue_share', 0)}%",
            f"{c.get('profit_margin', 0)}%"
        ])

    cat_table = Table(cat_rows, colWidths=[120, 80, 80, 70, 80, 90])
    cat_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366F1')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
    ]))
    story.append(cat_table)
    story.append(Spacer(1, 15))

    # Top Products Table
    story.append(Paragraph("Top 5 Products by Revenue", section_style))
    prod_headers = ["Product Name", "Category", "Revenue", "Units Sold", "Profit Margin"]
    prod_rows = [prod_headers]
    for p in top_products[:5]:
        prod_rows.append([
            p.get("product", ""),
            p.get("category", ""),
            p.get("revenue_formatted", ""),
            str(p.get("quantity", 0)),
            f"{p.get('profit_margin', 0)}%"
        ])

    prod_table = Table(prod_rows, colWidths=[150, 110, 100, 80, 80])
    prod_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('ALIGN', (2, 0), (-1, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
    ]))
    story.append(prod_table)

    doc.build(story)
    pdf_val = buffer.getvalue()
    buffer.close()
    return pdf_val
